import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#3e0500",
        "error": "#ba1a1a",
        "inverse-surface": "#31302d",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e5e2dd",
        "surface-container": "#f0ede8",
        "secondary-fixed-dim": "#c7bfff",
        "tertiary-container": "#d2a500",
        "primary-fixed": "#ffdad3",
        "surface-variant": "#e5e2dd",
        "secondary-fixed": "#e4dfff",
        "on-tertiary-container": "#4f3d00",
        "surface-dim": "#dcdad5",
        "surface-bright": "#fcf9f4",
        "on-tertiary-fixed-variant": "#584400",
        "tertiary-fixed-dim": "#f0c12c",
        "on-primary-fixed-variant": "#802918",
        "on-background": "#1c1c19",
        "surface": "#fcf9f4",
        "inverse-on-surface": "#f3f0eb",
        "on-surface": "#1c1c19",
        "outline-variant": "#ddc0ba",
        "tertiary-fixed": "#ffdf90",
        "on-tertiary": "#ffffff",
        "primary": "#9f402d",
        "surface-tint": "#9f402d",
        "on-primary-container": "#5a0d02",
        "tertiary": "#755b00",
        "on-error": "#ffffff",
        "surface-container-low": "#f6f3ee",
        "on-error-container": "#93000a",
        "inverse-primary": "#ffb4a5",
        "on-secondary-container": "#413886",
        "secondary": "#5d54a4",
        "primary-fixed-dim": "#ffb4a5",
        "on-secondary-fixed-variant": "#453b8a",
        "on-secondary-fixed": "#18065e",
        "background": "#fcf9f4",
        "on-tertiary-fixed": "#241a00",
        "secondary-container": "#b0a6fd",
        "primary-container": "#e2725b",
        "outline": "#89726d",
        "surface-container-high": "#ebe8e3",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#56423e",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
